---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: job-monitor
spec:
  rules:
  - host: job-monitor.local
    http:
      paths:
      - backend:
          serviceName: job-monitor
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: job-monitor
  labels:
    app: job-monitor
spec:
  selector:
    app: job-monitor
  ports:
  - name: app-port
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-monitor
  labels:
    app: job-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-monitor
  template:
    metadata:
      labels:
        app: job-monitor
    spec:
      containers:
      - name: job-monitor
        imagePullPolicy: Always
        image: iwilltry42/rancher2-job-monitor:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/.kube
          readOnly: true
        env:
        - name: RANCHER_URL
          value: 'http://rancher-ui.local'
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
